@startuml

title 3MF Volumetric Color & Scalar Fields

package Image
{
    Class Image3D
    {
        id : resourceID
        name : string
        rowcount : int
        colcount : int
        sheetcount : int
    }

    Class Image3DSheet
    {
        path : string (PNG)
    }

    Image3D *-- "1..*" Image3DSheet
}

package ScalarFields
{
    Class ScalarField
    {
        id: resourceID
    }

    Class ScalarFieldComposed extends ScalarField
    {
        blendmethod : string
        scalarfield1id : resourceID
        scalarfield2id : resourceID
        scalarmaskfieldid : resourceID
        factor1 : double
        factor2 : double
        transform1 : transform
        transform2 : transform
        transformmask : transform
    }

    Class ScalarFieldFromImage3D extends ScalarField
    {
        image3did : resourceID
        channel : string
        filter : string
        valueoffset: double
        valuescale: double
        tilestyleu : string
        tilestylev : string
        tilestylew : string
    }

    ScalarFieldComposed o-- "1..3" ScalarField
    ScalarFieldFromImage3D o-- "1" Image3D
}

package ColorFields
{
    Class ColorField
    {
        id: resourceID
    }

    Class ColorFieldComposed extends ColorField
    {
        blendmethod : string
        colorfield1id : resourceID
        colorfield2id : resourceID
        scalarmaskfieldid : resourceID
        factor1 : double
        factor2 : double
        transform1 : transform
        transform2 : transform
        transformmask : transform
    }

    Class ColorFieldFromImage3D extends ColorField
    {
        image3did : resourceID
        filter : string
        tilestyleu : string
        tilestylev : string
        tilestylew : string
    }

    ColorFieldComposed o-- "2" ColorField
    ColorFieldComposed o-- "0..1 mask" ScalarField
    ColorFieldFromImage3D o-- "1" Image3D
}

package VolumetricData
{
    Class VolumeData

    Class Boundary
    {
        transform : matrix
        solidthreshold : double
        scalarfield : resourceID
    }

    Class Color
    {
        transform : matrix
        colorfield : resourceID
    }

    Class Property
    {
        name : string
        transform : matrix
        scalarfield : resourceID
    }

    Class Composite
    {
        transform : matrix
    }

    Class MaterialMapping
    {
        scalarfield : resourceID
    }        

    VolumeData *-- "0..1" Boundary
    VolumeData *-- "0..1" Color
    VolumeData *-- "0..*" Property
    VolumeData *-- "0..1" Composite
    Composite *-- "1..*" MaterialMapping

    Boundary o-- "1" ScalarField
    Color o-- "1" ColorField
    Property o-- "1" ScalarField
    MaterialMapping o-- "1" ScalarField
}

Class Mesh
Mesh *-- VolumeData

@enduml
